import { App, requestUrl } from 'obsidian';
// @ts-ignore — generated by wasm-pack; no hand-written declaration needed
import pdfWasmInit, { render_to_pdf, typst_version } from './wasm/omd2typst-pdf-pkg/omd2typst_pdf_wasm.js';

// Version of the Typst compiler embedded in the PDF WASM binary.
export const PDF_WASM_TYPST_VERSION = '0.13.1';

// omd2typst release version that published this WASM artifact.
const PDF_WASM_RELEASE = '0.10.1';

const PDF_WASM_URL = `https://github.com/tIsGoud/Omd2Typst/releases/download/v${PDF_WASM_RELEASE}/omd2typst-pdf-compiler.wasm`;
// Include release version in filename so upgrading always pulls the matching binary.
const PDF_WASM_FILENAME = `omd2typst-pdf-compiler-v${PDF_WASM_RELEASE}.wasm`;

let initialised = false;

/** Absolute vault-relative path to the cached WASM file. */
function cachePath(pluginDir: string): string {
  return `${pluginDir}/${PDF_WASM_FILENAME}`;
}

/** Return true if the WASM binary is already cached in the vault. */
export async function isPdfWasmCached(app: App, pluginDir: string): Promise<boolean> {
  try {
    const stat = await app.vault.adapter.stat(cachePath(pluginDir));
    return stat !== null;
  } catch {
    return false;
  }
}

/**
 * Download the PDF WASM binary from GitHub releases and cache it in the vault.
 * Throws on network or write failure.
 */
export async function downloadPdfWasm(app: App, pluginDir: string): Promise<void> {
  // requestUrl routes through Electron's main process — bypasses CORS restrictions
  // that block fetch() from the renderer origin (app://obsidian.md).
  const response = await requestUrl({ url: PDF_WASM_URL });
  if (response.status !== 200) {
    throw new Error(`Download failed (${response.status}): ${PDF_WASM_URL}`);
  }
  const bytes = new Uint8Array(response.arrayBuffer);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  await (app.vault.adapter.write as any)(cachePath(pluginDir), bytes);
}

/**
 * Initialise the PDF WASM module — download if not cached, then instantiate.
 * Safe to call multiple times; no-op after first successful init.
 */
export async function ensurePdfWasm(app: App, pluginDir: string): Promise<void> {
  if (initialised) return;

  const path = cachePath(pluginDir);

  const cached = await isPdfWasmCached(app, pluginDir);
  if (!cached) {
    await downloadPdfWasm(app, pluginDir);
  }
  const buf: ArrayBuffer = await app.vault.adapter.readBinary(path);
  // Use async init — WebAssembly.instantiate() accepts buffers of any size on the
  // main thread, unlike the synchronous new WebAssembly.Module() used by initSync
  // which Electron blocks for payloads larger than 8 MB.
  await pdfWasmInit({ module_or_path: new Uint8Array(buf) });
  initialised = true;
}

/** Encode a Uint8Array as a standard base64 string. */
export function uint8ArrayToBase64(bytes: Uint8Array): string {
  let binary = '';
  const len = bytes.length;
  for (let i = 0; i < len; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary);
}

/**
 * Compile Typst source to PDF bytes using the WASM compiler.
 *
 * `typstSrc`     — Typst source string (from renderToTypst).
 * `vaultFiles`   — Map of vault-relative paths to UTF-8 file contents for any
 *                  `#import` paths in the source (e.g. the active template).
 * `binaryFiles`  — Map of vault-relative paths to base64-encoded binary content
 *                  (e.g. images referenced with `#image()`). Pass `{}` if none.
 */
export async function compileToPdfViaWasm(
  typstSrc: string,
  vaultFiles: Record<string, string>,
  binaryFiles: Record<string, string>,
  app: App,
  pluginDir: string,
): Promise<Uint8Array> {
  await ensurePdfWasm(app, pluginDir);
  return render_to_pdf(typstSrc, JSON.stringify(vaultFiles), JSON.stringify(binaryFiles));
}

/**
 * Return the Typst version string from the loaded WASM module.
 * Only valid after ensurePdfWasm() has been called.
 */
export function getWasmTypstVersion(): string {
  if (!initialised) return PDF_WASM_TYPST_VERSION;
  return typst_version();
}
