import { App, requestUrl } from 'obsidian';
// @ts-ignore — generated by wasm-pack; no hand-written declaration needed
import * as pdfWasmBg from './wasm/omd2typst-pdf-pkg/omd2typst_pdf_wasm_bg.js';

// Pull the specific functions we need from the namespace.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const { __wbg_set_wasm, render_to_pdf, typst_version } = pdfWasmBg as any;

// Version of the Typst compiler embedded in the PDF WASM binary.
export const PDF_WASM_TYPST_VERSION = '0.13.1';

// omd2typst release version that published this WASM artifact.
const PDF_WASM_RELEASE = '0.10.0';

const PDF_WASM_URL = `https://github.com/tIsGoud/Omd2Typst/releases/download/v${PDF_WASM_RELEASE}/omd2typst-pdf-compiler.wasm`;
const PDF_WASM_FILENAME = 'omd2typst-pdf-compiler.wasm';

let initialised = false;

/** Absolute vault-relative path to the cached WASM file. */
function cachePath(pluginDir: string): string {
  return `${pluginDir}/${PDF_WASM_FILENAME}`;
}

/** Return true if the WASM binary is already cached in the vault. */
export async function isPdfWasmCached(app: App, pluginDir: string): Promise<boolean> {
  try {
    const stat = await app.vault.adapter.stat(cachePath(pluginDir));
    return stat !== null;
  } catch {
    return false;
  }
}

/**
 * Download the PDF WASM binary from GitHub releases and cache it in the vault.
 * Throws on network or write failure.
 */
export async function downloadPdfWasm(app: App, pluginDir: string): Promise<void> {
  // requestUrl routes through Electron's main process — bypasses CORS restrictions
  // that block fetch() from the renderer origin (app://obsidian.md).
  const response = await requestUrl({ url: PDF_WASM_URL });
  if (response.status !== 200) {
    throw new Error(`Download failed (${response.status}): ${PDF_WASM_URL}`);
  }
  const bytes = new Uint8Array(response.arrayBuffer);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  await (app.vault.adapter.write as any)(cachePath(pluginDir), bytes);
}

/**
 * Initialise the PDF WASM module — download if not cached, then instantiate.
 * Safe to call multiple times; no-op after first successful init.
 */
export async function ensurePdfWasm(app: App, pluginDir: string): Promise<void> {
  if (initialised) return;

  const path = cachePath(pluginDir);

  const cached = await isPdfWasmCached(app, pluginDir);
  if (!cached) {
    await downloadPdfWasm(app, pluginDir);
  }
  const buf: ArrayBuffer = await app.vault.adapter.readBinary(path);
  const bytes = new Uint8Array(buf);

  // The PDF WASM imports JS callbacks from omd2typst_pdf_wasm_bg.js (e.g.
  // __wbindgen_cast_0000000000000001 for string handling). Passing the full
  // bg module as the import namespace satisfies all required imports.
  const result = await WebAssembly.instantiate(bytes as unknown as BufferSource, {
    './omd2typst_pdf_wasm_bg.js': pdfWasmBg,
  }) as WebAssembly.WebAssemblyInstantiatedSource;
  const { instance } = result;
  __wbg_set_wasm(instance.exports);
  initialised = true;
}

/**
 * Compile Typst source to PDF bytes using the WASM compiler.
 *
 * `typstSrc`    — Typst source string (from renderToTypst).
 * `vaultFiles`  — Map of vault-relative paths to UTF-8 file contents for any
 *                 `#import` paths in the source (e.g. the active template).
 */
export async function compileToPdfViaWasm(
  typstSrc: string,
  vaultFiles: Record<string, string>,
  app: App,
  pluginDir: string,
): Promise<Uint8Array> {
  await ensurePdfWasm(app, pluginDir);
  const filesJson = JSON.stringify(vaultFiles);
  return render_to_pdf(typstSrc, filesJson);
}

/**
 * Return the Typst version string from the loaded WASM module.
 * Only valid after ensurePdfWasm() has been called.
 */
export function getWasmTypstVersion(): string {
  if (!initialised) return PDF_WASM_TYPST_VERSION;
  return typst_version();
}
